# Generated by Django 4.0.10 on 2024-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
