# Generated by Django 4.0.10 on 2024-02-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_profile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_profile_link',
            new_name='facebook_profile_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='x_profile_link',
            new_name='twitter_profile_link',
        ),
    ]
