# Generated by Django 4.0.10 on 2024-02-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0003_rename_fb_profile_link_profile_facebook_profile_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='avatar.svg', upload_to=''),
        ),
    ]
